# Generated by Django 5.0.6 on 2024-06-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_finished_date_alter_task_report'),
        ('users', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_tasks', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
