# Generated by Django 5.0.6 on 2024-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_executor_alter_task_finished_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
